[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ultralytics = "^8.0.196"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
